apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      project: account-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        project: account-deploy
    spec:
      containers:
        - name: account-pod
          image: 495360382884.dkr.ecr.us-west-2.amazonaws.com/account:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1024Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "0.2"

