server:
  port: 8889
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/order
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: INFO
    springframework:
      transaction: DEBUG
#    org:
#      springframework:
#        kafka: TRACE
    org.hibernate:
      transaction: DEBUG
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
debug: true